version: "3.9"
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=kalenderium
      - POSTGRES_PASSWORD=kartaca2022
      - POSTGRES_DB=calendar
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://kalenderium:kartaca2022@postgres:5432/calendar?sslmode=disable
    depends_on:
      - postgres
    command: [ "/app/calendar" ]